name: KernWarden CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Verify dependencies
        run: go mod tidy && git diff --exit-code

      - name: Run static analysis
        run: make vet

      - name: Build binary
        run: make build